### ISSUE TITLE
accumulate laser scans

### ISSUE THREAD

**Issue by Citygity** [soulslicer/kitti_depthmap#1]
Thank you for your great job! I'm tring to build depth using your project. I found that depth are not dense enough and wrong points caused by alignment of different sensors. will you implement  laser scans accumulation for a denser depth map and disparity consistency check？

**Comment by soulslicer** [comment]
this module is simply converting the ptcloud into a depthmap for a single scene. anything else you have to implement yourself.

**Comment by Citygity** [comment]
Thanks for your apply.  I found that  the official repo provide c++ codes for accumulation.
